---

- name: user and group handling
  when:
    - registry_ui_system_user != "root" or registry_ui_system_group != "root"
  block:
    - name: create registry group
      ansible.builtin.group:
        name: "{{ registry_ui_system_group }}"
        state: present
        system: true
      when:
        - registry_ui_system_group != "root"

    - name: create registry user
      ansible.builtin.user:
        name: "{{ registry_ui_system_user }}"
        groups: "{{ registry_ui_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: "{{ registry_ui_data_dir }}"
      when:
        - registry_ui_system_user != "root"

- name: deploy and activate registry-ui version {{ registry_ui_version }}
  when:
    - not running_in_check_mode
  bodsch.core.deploy_and_activate:
    src_dir: "{{ registry_ui_local_tmp_directory }}"
    install_dir: "{{ registry_ui_install_path }}"
    link_dir: "/usr/bin"
    remote_src: "{{ ('true' if registry_ui_direct_download else 'false') | bool }}"
    owner: "{{ registry_ui_system_user }}"
    group: "{{ registry_ui_system_group }}"
    mode: "0755"
    items:
      - name: registry-ui
  notify:
    - restart registry-ui
  register: __activate_bin

- name: detect static template
  ansible.builtin.stat:
    path: "{{ registry_ui_data_dir }}/templates/base.html"
  register: stat_static_template

- name: propagate static files
  when:
    - stat_static_template.stat is defined and not stat_static_template.stat.exists | default('false') | bool or
      __activate_bin.changed | bool
  ansible.builtin.copy:
    src: "{{ registry_ui_local_tmp_directory }}/{{ item }}/"
    dest: "{{ registry_ui_data_dir }}/{{ item }}/"
    mode: 0644
    owner: "{{ registry_ui_system_user }}"
    group: "{{ registry_ui_system_group }}"
    remote_src: "{{ 'true' if registry_ui_direct_download else 'false' }}"
  loop:
    - static
    - templates
  notify:
    - restart registry-ui

- name: systemd
  when:
    - ansible_facts.service_mgr | lower == "systemd"
  block:
    - name: create registry-ui run configuration
      ansible.builtin.template:
        src: "registry-ui.j2"
        dest: "{{ registry_ui_defaults_directory }}/registry-ui"
        force: true
        owner: root
        group: "{{ registry_ui_system_group }}"
        mode: "0640"
      notify:
        - restart registry-ui

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/registry-ui.service.j2"
        dest: "{{ systemd_lib_directory }}/registry-ui.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - daemon-reload

- name: openrc
  when:
    - ansible_facts.service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/registry-ui.j2"
        dest: "/etc/conf.d/registry-ui"
        owner: root
        group: root
        mode: "0644"

    - name: create openrc init file
      ansible.builtin.template:
        src: "init/openrc/init.d/registry-ui.j2"
        dest: "/etc/init.d/registry-ui"
        owner: root
        group: root
        mode: "0750"

- name: create custom fact file
  bodsch.core.facts:
    name: registry_ui
    facts:
      version: "{{ registry_ui_version }}"

...
