---

namespace: bodsch
name: docker

version: 1.4.0

readme: README.md

authors:
  - Bodo Schulz (@bodsch)

description: A collection of Ansible roles for the Docker universe.

license:
  - Apache-2.0

license_file: ''

tags:
  - system
  - docker
  - container

dependencies:
  bodsch.core: ">=2.2.1"
  bodsch.scm: ">=1.4.6"
  community.docker: "*"
  community.general: ">=6.5.0"

repository: https://github.com/bodsch/ansible-collection-docker
documentation: https://github.com/bodsch/ansible-collection-docker/README.md
homepage: https://github.com/bodsch/ansible-collection-docker
issues: https://github.com/bodsch/ansible-collection-docker/issues

build_ignore:
  - "galaxy.yml"
  - "*.pyc"
  - "*.retry"
  - ".ansible-lint"
  - ".editorconfig"
  - ".flake8"
  - ".gitignore"
  - ".yamllint"
  - ".github"
