---

- name: prepare
  ansible.builtin.import_tasks: prepare.yml
  tags:
    - compose

- name: download
  ansible.builtin.import_tasks: download.yml
  tags:
    - compose_download
    - compose_install

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - compose_install
...
