---

- name: execute post tasks
  ansible.builtin.command: |
    {{ item }}
  changed_when: false
  register: _post_task_output
  loop: "{{ container_post_tasks }}"
  tags:
    - container_exec_post_tasks

- name: result
  ansible.builtin.debug:
    msg:
      - "{{ item.stdout }}"
  loop: "{{ _post_task_output.results }}"
  loop_control:
    label: "{{ item.item }}"
  tags:
    - container_exec_post_tasks

...
