---

docker_dependencies:
  - acl
  - python3-pip
  - python3-docker
  - python3-requests
  - python3-urllib3
  # - python3-virtualenv
  - net-tools
  - iproute2
  - gpg

docker_defaults_python_packages: []

...
