---

docker_client_defaults: &DOCKER_CLIENTS_DEFAULTS
  formats:
    ps:
      - ".ID"
      - ".Names"
      - ".Status"
      - ".RunningFor"
      - ".Ports"
    images:
      - ".ID"
      - ".Size"
      - ".Repository"
      - ".Tag"
      - ".CreatedAt"

docker_client_config:
  ## the location we should push client configuration
  - location: "/root/.docker/config.json"
    enabled: true
    <<: *DOCKER_CLIENTS_DEFAULTS
    auths:
      "registry.gitfoo.tld":
        auth: amVua2luczpydWJiZWwtZGllLWthdHotZHUtZHVtbXNjaHfDpHR6ZXIxCg==
      "test.tld":
        username: "FOO-was-sonst"
        password: "ja-toll-schon-wieder-alles-scheisse!"

    ## the location we should push client configuration
  - location: "/var/tmp/foo/config.json"
    enabled: false
    <<: *DOCKER_CLIENTS_DEFAULTS
    auths:
      "test.tld":
        username: "FOO-was-sonst"
        password: "ja-toll-schon-wieder-alles-scheisse!"

docker_config:
  data_root: /opt/docker
  max_concurrent_downloads: 10
  debug: false
  log_opts:
    "cache-disabled": true
    "cache-compress": "true"
    "cache-max-file": 5
  experimental: false
  hosts:
    - unix:///run/docker.sock
    - tcp://0.0.0.0:3485
  fixed_cidr: "192.168.9.0/24"
  dns_search:
    - docker.local
  metrics_addr: "127.0.0.1:9999"
  tls:
    verify: true
    ca_cert: "{{ snakeoil_extract_to }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.crt"
    cert: "{{ snakeoil_extract_to }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.pem"
    key: "{{ snakeoil_extract_to }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.key"
  # works not in the molecule docker environment
  # storage_driver: overlay2
  # storage_opts:
  #   - overlay2.size=10G

...
