---

registry_ui_main_version: "{{ registry_ui_version[0:3] }}"

registry_ui_install_path: /usr/local/bin/registry-ui/{{ registry_ui_version }}

registry_ui_delegate_to: localhost

registry_ui_local_tmp_directory: "{{
  lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
  default(lookup('env', 'HOME') ~ '/.cache/ansible/registry-ui', true) }}/{{ registry_ui_version }}"

registry_ui_requirements:
  - iproute2
  - gzip

# ----------------------------------------------------------------------------------------

registry_ui_defaults_service:
  log_level: info

registry_ui_defaults_listen:
  address: 127.0.0.1
  port: 8000

registry_ui_defaults_base_path: /ui

registry_ui_defaults_registry:
  url: https://docker-registry.local:5000
  verify_tls: true
  username: ""  #  user
  password: ""  #  pass
  password_file: ""  #  /run/secrets/registry_password_file

registry_ui_defaults_event:
  listener_token: ""  #  token
  retention_days: 7
  database:
    driver: sqlite3  #  sqlite3 or mysql
    location: ""  #  data/registry_events.db
    username:
    password:
    hostname: 127.0.0.1:3306
    schemaname: docker_events
  deletion_enabled: true
  anyone_can_view: true

registry_ui_defaults_cache:
  refresh_interval: 10

registry_ui_defaults_delete:
  anyone_can_delete: false
  admins: []

registry_ui_defaults_admins: []

registry_ui_defaults_purge:
  tags_keep_days: 90
  tags_keep_count: 2
  tags_keep_regexp: ''
  tags_keep_from_file: ''
  tags_schedule: ''

# ----------------------------------------------------------------------------------------

registry_ui_archive: "registry-ui-{{ registry_ui_version }}-{{ ansible_facts.system }}-{{ system_architecture }}.tar.gz"
registry_ui_checksum_url: "{{ registry_ui_release_download_url }}/download/{{ registry_ui_version }}/{{ registry_ui_archive }}.sha256"

registry_ui_defaults_directory: /etc/default

go_arch_map:
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'

system_architecture: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"

systemd_lib_directory: /lib/systemd/system

...
