---

- name: update
  hosts: instance
  any_errors_fatal: false
  gather_facts: true

  vars:
    container:
      - name: busybox
        hostname: busybox
        image: busybox:latest
      - name: busybox-2
        hostname: busybox-2
        image: busybox:latest

  roles:
    - role: bodsch.docker.container

...
