---

role_name_check: 1

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: "${INSTANCE:-instance}"
    image: "bodsch/ansible-${DISTRIBUTION:-debian:12}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:ro
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2:rw
    capabilities: ALL

provisioner:
  name: ansible
  ansible_args:
    - --diff
    - -v
  config_options:
    defaults:
      deprecation_warnings: true
      stdout_callback: yaml
      callbacks_enabled: profile_tasks
      gathering: smart
      fact_caching: jsonfile
      fact_caching_timeout: 8640
      fact_caching_connection: ansible_facts

scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
