---

htpasswd_credentials_path: /etc/nginx/htpasswd.d

htpasswd_credentials:

  - path: "{{ htpasswd_credentials_path }}/.admin-passwdfile"
    users:
    - username: admin
      password: ZRhgqhaAjdbuFXj2PLJTzYy5PrRsStNaeYWd9c3Ze3
    - username: registry
      password: registry

  - path: /etc/docker/registry/.registry-passwdfile
    mode: "u=rw,g=r,o-r"
    group: registry
    users:
    - username: registry
      password: registry
      crypt_scheme: md5_crypt
...
