---

- name: add docker-ce apt sources
  when:
    - ansible_facts.os_family | lower == 'debian'
  bodsch.core.apt_sources:
    name: docker-cd
    filename: docker-ce.sources
    uris:
      - https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}
    suites: "{{ ansible_facts.distribution_release | lower }}"
    components:
      - stable
    signed_by: /usr/share/keyrings/docker-archive-keyring.gpg
    key:
      method: download
      url: "https://download.docker.com/linux/debian/gpg"
      dest: "/usr/share/keyrings/docker-archive-keyring.gpg"
      dearmor: true
      validate: true
    update_cache: true

...
