---

- name: debain based
  when:
    - ansible_os_family | lower == 'debian'
  block:
    - name: add docker apt key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /usr/share/keyrings/docker.gpg
        mode: '0644'
      register: docker_apt_key

    - name: add docker apt repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/docker.sources
        content: |
          Types: deb
          URIs: https://download.docker.com/linux/debian
          Suites: trixie
          Components: stable
          Signed-By: /usr/share/keyrings/docker.gpg
        mode: '0644'
      register: docker_apt_repository

    - name: update package cache
      ansible.builtin.package:
        update_cache: true
      when:
        - docker_apt_key.changed or
          docker_apt_repository.changed

...
