---

- name: clean apt cache (ansible < 2.13)  # noqa command-instead-of-module
  listen: clean apt cache
  ansible.builtin.command: |
    apt-get clean
  register: apt_clean
  changed_when: apt_clean.rc != 0
  failed_when: apt_clean.rc != 0
  when: "ansible_version.full is version_compare('2.13', '<')"

- name: clean apt cache (ansible >= 2.13)
  listen: clean apt cache
  ansible.builtin.apt:
    clean: true
  when: "ansible_version.full is version_compare('2.13', '>=')"

- name: created application directories  # noqa no-handler
  ansible.builtin.debug:
    msg: "{{ _created_directories.created_directories }}"
  when:
    - _created_directories.changed
    - _created_directories.created_directories is defined

- name: created container volumes and mountpoints  # noqa no-handler
  ansible.builtin.debug:
    msg: "{{ _created_directories.created_directories }}"
  when:
    - _created_directories.changed
    - _created_directories.created_directories is defined

- name: container restart necessary  # noqa no-handler
  ansible.builtin.set_fact:
    container_update_needed: true
  when:
    - _container_data.changed

- name: update container for recreate running docker instance
  ansible.builtin.set_fact:
    container: "{{ _container_data.container_data }}"
  when:
    - _container_data is defined
    - _container_data.container_data is defined

- name: created environnments or properties  # noqa no-handler
  ansible.builtin.debug:
    msg: "{{ _container_data.msg }}"
  when:
    - _container_data is defined
    - _container_data.msg is defined
    - _container_data.changed

...
