---

- name: information
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: arch- / artixlinux
      when:
        - ansible_distribution | lower == 'archlinux' or
          ansible_os_family | lower == 'artix linux'
      block:
        - name: update pacman system
          ansible.builtin.command: |
            pacman --refresh --sync --sysupgrade --noconfirm
          register: pacman
          changed_when: pacman.rc != 0
          failed_when: pacman.rc != 0

        - name: create depends service
          ansible.builtin.copy:
            mode: 0755
            dest: /etc/init.d/net
            content: |
              #!/usr/bin/openrc-run
              true
          when:
            - ansible_os_family | lower == 'artix linux'

    - name: make sure python3-apt is installed (only debian based)
      ansible.builtin.package:
        name:
          - python3-apt
        state: present
      when:
        - ansible_os_family | lower == 'debian'

    - name: update package cache
      become: true
      ansible.builtin.package:
        update_cache: true


    - name: environment
      ansible.builtin.debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

- name: prepare container
  hosts: all
  gather_facts: true

  roles:
    - role: bodsch.docker.docker

- name: deploy first container
  hosts: instance
  any_errors_fatal: true
  gather_facts: true

  roles:
    - role: bodsch.docker.container
      vars:
        container:
          - name: hello-world
            hostname: hello-world
            image: hello-world:latest
            properties:
              #
              publisher.maxRecursionDepth: 200
              # user and password for login to the staging serve
              replicator.user: 'replicator'
              replicator.password: 'replicator'
