---

container_network:
  - name: test
    subnet: 172.3.27.0/24
    gateway: 172.3.27.2
    iprange: 172.3.27.0/26

container_fail:
  error_at_launch: false

container_custom_tasks: []

container_pre_tasks: []
#  - /usr/local/bin/list_all_images.sh

container_post_tasks: []
#  - /usr/local/bin/remove_untagged_images.sh
#  - /usr/local/bin/parse_container_fact.sh

_images:
  image_1: "busybox:latest"
  image_2: "busybox:uclibc"
  image_3: "hello-world:linux"
  image_4: "busybox:stable"
  image_5: "busybox:1.36.1-uclibc"
  image_6: "busybox:1.36.1"
  image_7: "bash:devel-alpine3.18"
  image_8: "hello-world:latest"
  image_9: "busybox:latest"
  image_10: "busybox:latest"
  image_11: "bash:4.4.23"

_container_defaults: &CONTAINER_DEFAULTS
  restart_policy: always
  labels:
    watchdog: "false"
  log_options:
    labels: "service"
    max-size: "1m"
    max-file: "2"

container: "{{
  container_1 |
  union(container_2 | default([])) |
  union(container_3 | default([])) |
  union(container_4 | default([])) |
  union(container_5 | default([])) |
  union(container_6 | default([])) |
  union(container_7 | default([])) |
  union(container_8 | default([])) |
  union(container_9 | default([])) |
  union(container_10 | default([])) |
  union(container_11 | default([]))
  }}"

container_1:
  - name: busybox-1
    hostname: busybox-1
    image: "{{ _images.image_1 }}"
    volumes:
      - /run/docker.sock:/tmp/docker.sock:ro
      - /dev/foo:/dev/foo:ro
      - /tmp/busybox-1/nginx:/tmp/nginx:ro
      - /tmp/busybox-1/testing3:/var/tmp/testing3:rw|{owner="1001",group="1000"}
      - /tmp/busybox-1/testing4:/var/tmp/testing4|{owner="1001",mode="0700"}
      - /tmp/busybox-1/testing5:/var/tmp/testing5|{owner="1001",mode="0700",ignore=True}
      - /tmp/busybox-1/testing6:/var/tmp/testing6:ro|{owner="1001",group="1000"}
    mounts:
      - source: /tmp/busybox-1/testing1
        target: /var/tmp/testing1
        type: bind
        source_handling:
          create: true
          owner: "1000"
          group: "1000"
          mode: "0750"
      - source: /tmp/busybox-1/testing2
        target: /var/tmp/testing2
        type: bind
        source_handling:
          create: true
          owner: "800"
          group: "800"
          mode: "0700"
      - source: /opt/busybox-1/registry
        target: /opt/data
        type: bind
        source_handling:
          create: true
          owner: "1000"
          group: "1000"
          mode: "0750"
      - source: "{{ container_env_directory }}/registry/config.yml"
        target: /etc/docker/registry/config.yml
        type: bind
        read_only: true
        source_handling:
          create: false

container_2:
  - name: busybox-2
    <<: *CONTAINER_DEFAULTS
    hostname: busybox-2
    image: "{{ _images.image_2 }}"
    mounts:
      - source: /tmp/busybox-2/testing1
        target: /var/tmp/testing1
        type: bind
        source_handling:
          create: true
          owner: "1000"
          group: "1000"
          mode: "0750"
      - source: /tmp/busybox-2/testing2
        target: /var/tmp/testing2
        type: bind
        source_handling:
          create: true
          owner: "800"
          group: "999"
          mode: "0700"
    environments:
      VIRTUAL_HOST: busybox-2.local
      # TEST_WORF: true
      DBA_HOST: database
      DBA_USER: username

container_3:
  - name: hello-world-1
    <<: *CONTAINER_DEFAULTS
    state: stopped
    hostname: hello-world-1
    image: "{{ _images.image_3 }}"
    properties:
      publisher.maxRecursionDepth: 600
      # user and password for login to the staging serve
      replicator.user: 'replicator'
      replicator.password: 'replicator'
      # replicator.domain: ''
      replicator.tmp_dir: 'var/tmp'
    environments:
      VIRTUAL_HOST: hello-world-1.local

container_4:
  - name: busybox-4
    <<: *CONTAINER_DEFAULTS
    state: absent
    hostname: busybox-4
    image: "{{ _images.image_4 }}"
    environments:
      VIRTUAL_HOST: busybox-4.local

container_5:
  - name: busybox-5
    <<: *CONTAINER_DEFAULTS
    hostname: busybox-5
    image: "{{ _images.image_5 }}"
    restart: "false"
    restart_policy: "no"
    environments:
      VIRTUAL_HOST: busybox-5.local
    property_files:
      - name: publisher.properties
        properties:
          replicator.user: 'replicator'
          replicator.password: 'RSActgjk3shTcgosJzn4vT2.Z9i47QLV'
          replicator.domain: 'localhost'
          replicator.tmp_dir: 'var/tmp'
      - name: database.properties
    properties:
      #
      publisher.maxRecursionDepth: 900
      # user and password for login to the staging serve
      replicator.user: 'replicator'
      replicator.password: 'RSActgjk3shTcgosJzn4vT2.Z9i47QLV'
      replicator.domain: 'localhost'
      replicator.tmp_dir: 'var/tmp'

container_6:
  - name: busybox-6
    <<: *CONTAINER_DEFAULTS
    hostname: busybox-6
    image: "{{ _images.image_6 }}"
    restart: "false"
    environments:
      VIRTUAL_HOST: busybox-6.local
    property_files:
      - name: publisher.properties
        properties:
          replicator.user: 'replicator'
          replicator.password: 'RSActgjk3shTcgosJzn4vT2.Z9i47QLV'
          replicator.domain: 'localhost'
          replicator.tmp_dir: 'var/tmp'
      - name: database.properties
    properties:
      #
      publisher.maxRecursionDepth: 900
      # user and password for login to the staging serve
      replicator.user: 'replicator'
      replicator.password: 'RSActgjk3shTcgosJzn4vT2.Z9i47QLV'
      replicator.domain: 'localhost'
      replicator.tmp_dir: 'var/tmp'

container_7:
  - name: busybox-7
    <<: *CONTAINER_DEFAULTS
    hostname: busybox-7
    image: "{{ _images.image_7 }}"
    restart: "false"
    environments:
      VIRTUAL_HOST: busybox-7.local
    property_files:
      - name: publisher.properties
        properties:
          replicator.user: 'replicator'
          replicator.password: 'RSActgjk3shTcgosJzn4vT2.Z9i47QLV'
          replicator.domain: 'localhost'
          replicator.tmp_dir: 'var/tmp'
      - name: database.properties
    properties:
      #
      publisher.maxRecursionDepth: 900
      # user and password for login to the staging serve
      replicator.user: 'replicator'
      replicator.password: 'RSActgjk3shTcgosJzn4vT2.Z9i47QLV'
      replicator.domain: 'localhost'
      replicator.tmp_dir: 'var/tmp'

container_8:
  - name: busybox-8
    <<: *CONTAINER_DEFAULTS
    state: present
    hostname: busybox-8
    image: "{{ _images.image_8 }}"
    restart: "false"
    environments:
      VIRTUAL_HOST: busybox-8.local
    property_files:
      - name: publisher.properties
        properties:
          replicator.user: 'replicator'
          replicator.password: 'RSActgjk3shTcgosJzn4vT2.Z9i47QLV'
          replicator.domain: 'localhost'
          replicator.tmp_dir: 'var/tmp'
      - name: database.properties
    properties:
      #
      publisher.maxRecursionDepth: 900
      # user and password for login to the staging serve
      replicator.user: 'replicator'
      replicator.password: 'RSActgjk3shTcgosJzn4vT2.Z9i47QLV'
      replicator.domain: 'localhost'
      replicator.tmp_dir: 'var/tmp'

container_9:
  - name: busybox-9
    <<: *CONTAINER_DEFAULTS
    state: present
    hostname: busybox-9
    image: "{{ _images.image_9 }}"
    mounts:
      - source: /tmp/busybox-9/testing1
        target: /var/tmp/testing1
        type: bind
        source_handling:
          create: true
          owner: "1000"
          group: "1000"
          mode: "0750"
      - source: /tmp/busybox-9/testing2
        target: /var/tmp/testing2
        type: bind
        source_handling:
          create: true
          owner: "800"
          group: "999"
          mode: "0700"
    environments:
      VIRTUAL_HOST: busybox-9.local
    property_files:
      - name: publisher.properties
        properties:
          replicator.user: 'replicator'
          replicator.password: 'RSActgjk3shTcgosJzn4vT2.Z9i47QLV'
          replicator.domain: 'localhost'
          replicator.tmp_dir: 'var/tmp'
      - name: database.properties
    properties:
      #
      publisher.maxRecursionDepth: 900
      # user and password for login to the staging serve
      replicator.user: 'replicator'
      replicator.password: 'RSActgjk3shTcgosJzn4vT2.Z9i47QLV'
      replicator.domain: 'localhost'
      replicator.tmp_dir: 'var/tmp'

container_10:
  - name: busybox-10
    <<: *CONTAINER_DEFAULTS
    state: only_present
    hostname: busybox-10
    image: "{{ _images.image_10 }}"
    restart: "false"
    environments:
      VIRTUAL_HOST: busybox-10.local
    property_files:
      - name: publisher.properties
        properties:
          replicator.user: 'replicator'
          replicator.password: 'RSActgjk3shTcgosJzn4vT2.Z9i47QLV'
          replicator.domain: 'localhost'
          replicator.tmp_dir: 'var/tmp'
      - name: database.properties
    properties:
      #
      publisher.maxRecursionDepth: 900
      # user and password for login to the staging serve
      replicator.user: 'replicator'
      replicator.password: 'RSActgjk3shTcgosJzn4vT2.Z9i47QLV'
      replicator.domain: 'localhost'
      replicator.tmp_dir: 'var/tmp'

container_11:
  - name: busybox-11
    <<: *CONTAINER_DEFAULTS
    state: present
    hostname: busybox-11
    image: "{{ _images.image_11 }}"
    restart: "false"
    environments:
      VIRTUAL_HOST: busybox-11.local
    property_files:
      - name: publisher.properties
        properties:
          replicator.user: 'replicator'
          replicator.password: 'RSActgjk3shTcgosJzn4vT2.Z9i47QLV'
          replicator.domain: 'localhost'
          replicator.tmp_dir: 'var/tmp'
      - name: database.properties
    properties:
      #
      publisher.maxRecursionDepth: 900
      # user and password for login to the staging serve
      replicator.user: 'replicator'
      replicator.password: 'RSActgjk3shTcgosJzn4vT2.Z9i47QLV'
      replicator.domain: 'localhost'
      replicator.tmp_dir: 'var/tmp'
    mounts:
      - source: /tmp/busybox-11/testing1
        target: /var/tmp/testing1
        type: bind
        source_handling:
          create: true
          owner: "1000"
          group: "1000"
          mode: "0750"
      - source: /tmp/busybox-11/testing2
        target: /var/tmp/testing2
        type: bind
        source_handling:
          create: true
          owner: "800"
          group: "800"
          mode: "0700"
      - source: /opt/busybox-11/registry
        target: /opt/data
        type: bind
        source_handling:
          create: true
          owner: "1000"
          group: "1000"
          mode: "0750"

...
