---
name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'

env:
  COLLECTION_NAMESPACE: bodsch
  COLLECTION_NAME: docker

jobs:
  arch:
    name: "${{ matrix.collection_role }} - ${{ matrix.image }}, ansible: ${{ matrix.ansible-version }}, python: ${{ matrix.python_version }}"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - archlinux:latest
        ansible-version:
          - '6.7'
          - '7.5'
          - '8.5'
        python_version:
          - "3.10.11"
          - "3.11.3"
        scenario:
          - default
        collection_role:
          - docker
          - container
          - registry
          - registry_ui
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 🐍 set up python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python_version }}"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: Install collection
        run: |
          make \
            install

      - name: test with tox
        run: |
          make \
            test \
              -e TOX_ANSIBLE="ansible_${{ matrix.ansible-version }}" \
              -e DISTRIBUTION="${{ matrix.image }}" \
              -e COLLECTION_ROLE="${{ matrix.collection_role }}" \
              -e COLLECTION_SCENARIO="${{ matrix.scenario }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}

  deb:
    name: "${{ matrix.collection_role }} - ${{ matrix.image }}, ansible: ${{ matrix.ansible-version }}, python: ${{ matrix.python_version }}"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:11
          - debian:12
          - ubuntu:20.04
          - ubuntu:22.04
        ansible-version:
          - '6.7'
          - '7.5'
          - '8.5'
        python_version:
          - "3.10.11"
          - "3.11.3"
        scenario:
          - default
        collection_role:
          - docker
          - container
          - registry
          - registry_ui
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 🐍 set up python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python_version }}"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: Install collection
        run: |
          make \
            install

      - name: test with tox
        run: |
          make \
            test \
              -e TOX_ANSIBLE="ansible_${{ matrix.ansible-version }}" \
              -e DISTRIBUTION="${{ matrix.image }}" \
              -e COLLECTION_ROLE="${{ matrix.collection_role }}" \
              -e COLLECTION_SCENARIO="${{ matrix.scenario }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}
